INSERT INTO FISH (NAME, PRICE, QUANTITY) VALUES ('Aaravi', 10, 11);
INSERT INTO FISH (NAME, PRICE, QUANTITY) VALUES ('Ring Fish', 11, 100);
INSERT INTO FISH (NAME, PRICE, QUANTITY) VALUES ('Squid', 1, 40);
