INSERT INTO ORDER_DETAILS (PRICE, QUANTITY, USER_ID, FISH_ID) VALUES ( 10, 11, 1, 1);
INSERT INTO ORDER_DETAILS (PRICE, QUANTITY, USER_ID, FISH_ID) VALUES ( 30, 1, 1, 2);
INSERT INTO ORDER_DETAILS (PRICE, QUANTITY, USER_ID, FISH_ID) VALUES ( 5, 190, 2, 3);

